stages:
  - build
  - style
  - integration_tests
  - deploy

build-code:
  stage: build
  script:
    - cd src/simpleBash/cat
    - make 
    - cd ../grep
    - make 
  artifacts:
    paths:
      - src/simpleBash/cat/s21_cat
      - src/simpleBash/grep/s21_grep
    expire_in: 30 days

style-check-cat:
  stage: style
  script:
    - cd src/simpleBash/cat
    - if clang-format -n -style=Google *.c *.h; then echo "Code style cat is OK"; else echo "Code style check failed" && exit 1; fi
  artifacts:
    paths:
      - src/simpleBash/cat/*.c
      - src/simpleBash/cat/*.h
    expire_in: 30 days

style-check-grep:
  stage: style
  script:
    - cd src/simpleBash/grep
    - if clang-format -n -style=Google *.c *.h; then echo "Code style grep is OK"; else echo "Code style check failed" && exit 1; fi
  artifacts:
    paths:
      - src/simpleBash/grep/*.c
      - src/simpleBash/grep/*.h
    expire_in: 30 days

integration-tests:
  stage: integration_tests
  script:
    - cd src/simpleBash/cat
    - bash script_cat.sh; status=$?; [[ $status == 0 ]] && echo "Integration tests cat is OK" || (echo "Integration tests cat failed" && exit 1)
    - cd ../grep
    - bash test_grep.sh; status=$?; [[ $status == 0 ]] && echo "Integration tests grep is OK" || (echo "Integration tests grep failed" && exit 1)
  dependencies:
    - build-code
    - style-check-cat
    - style-check-grep

Deploy:
  stage: deploy
  when: manual
  script:
    - chmod +x deploy.sh
    - bash deploy.sh; status=$?; [[ $status == 0 ]] && echo "Deploy is OK" || (echo "Deploy failed" && exit 1)
